SELECT COUNT(*) AS open_positions
FROM HISTORIE_V hv1
LEFT JOIN HISTORIE_V hv2
  ON hv1.LHMNR = hv2.LHMNR
  AND hv1.ZUG_ID = hv2.ZUG_ID 
  AND hv2.TYP_ID = '47'
WHERE hv1.TRANSPORTTASKQUELLE LIKE 'BGL%' 
  AND hv1.TRANSPORTTASKZIEL LIKE '%FIN_AP%'
  AND hv1.TYP_ID = '42' 
  AND (hv1.LAGBEZ != 'AKL' OR hv1.LAGBEZ IS NULL) 
  AND hv1.ZUGGRUPPE_SENDER = 'BESTANDFREIGABE'
  AND hv1.CREATED >= (SYSDATE - 5)
  AND hv2.LHMNR IS NULL