WITH 
t1_main AS (
    SELECT *
    FROM HISTORIE_V
    WHERE TRANSPORTTASKQUELLE = 'WE' 
      AND TRANSPORTREQUESTZIEL LIKE '%BSF_O%'
      AND TYP_ID = '42' 
      AND LAGBEZ = 'Wareneingang'
      AND CREATED >= (SYSDATE - 2)
),


t2_typ47 AS (
    SELECT DISTINCT TRANSPORTLHMNR, ZUG_ID
    FROM HISTORIE_V
    WHERE TYP_ID = '47'
),

t3_typ39 AS (
    SELECT DISTINCT TRANSPORTLHMNR, ZUG_ID
    FROM HISTORIE_V
	WHERE TYP_ID = '39'
)

SELECT COUNT(*) AS WE_BESF_OV
FROM t1_main t1
LEFT JOIN t2_typ47 t2 
  ON t1.TRANSPORTLHMNR = t2.TRANSPORTLHMNR
  AND t1.ZUG_ID = t2.ZUG_ID  
LEFT JOIN t3_typ39 t3 
  ON t1.TRANSPORTLHMNR = t3.TRANSPORTLHMNR
  AND t1.ZUG_ID = t3.ZUG_ID  
WHERE t2.TRANSPORTLHMNR IS NULL 
  AND t3.TRANSPORTLHMNR IS NULL