-- AKL lCCONTENT -- 

SELECT
	TO_CHAR("CREATED", 'DD.MM.YYYY') AS date_only, 
    TO_CHAR("CREATED", 'YYYY_MM') AS year_cw, 
    SUM(MENGE) AS quantity
FROM HISTORIE_V hv 
WHERE hv.LAGBEZ = 'Sorter' 
AND hv."CREATED" BETWEEN TO_DATE(:start_datetime, 'DD.MM.YYYY HH24:MI:SS') 
AND TO_DATE(:end_datetime, 'DD.MM.YYYY HH24:MI:SS')
AND hv.HOSTAUFTRNR LIKE 'LCCONTENT%'
AND hv.MENGE = 1
GROUP BY TO_CHAR("CREATED", 'DD.MM.YYYY'), TO_CHAR("CREATED", 'YYYY_MM') 
ORDER BY date_only
